service: serverless-golang-starter-backend

frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x
  region: us-west-2
  stage: ${opt:stage, 'dev'}
  profile: ${self:custom.awsProfile.${self:provider.stage}}
  environment: ${file(environment.yml)}
  
package:
  individually: true
  exclude:
    - ./**

functions:
  hello:
    handler: bin/user
    package:
      include:
        - ./bin/user
    events:
      - http:
          path: user
          method: POST
      - http:
          path: user/{id}
          method: GET


plugins:
  # - serverless-export-env
  - serverless-offline
  
custom:
  secrets: ${file(secrets.${opt:stage, self:provider.stage}.yml)}
  awsProfile:
    dev: default
    prod: default